[package]
name = "frame-flow"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.5.0"
anyhow = "1.0.41"
serde = { version = "1.0.126", features = ["derive"] }
json5 = "0.3.0"
structopt = "0.3.21"
tch-serde = "0.6.0"
rand = "0.8.4"
itertools = "0.10.1"
iterator-ext = "0.2.0"
unzip-n = "0.1.2"
approx = "0.5.0"
tch-tensor-like = "0.4.0"
tokio = { version = "1.7.1", features = ["fs"] }
tokio-stream = { version = "0.1.6", features = ["fs"] }
futures = "0.3.15"
par-stream = { version = "0.3.1", features = ["runtime_tokio"] }
csv = "1.1.6"
indexmap = "1.6.2"
collected = "0.3.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
# opentelemetry-jaeger = "0.14.0"
# tracing-opentelemetry = "0.13.0"
noisy_float = { version = "0.2.0", features = ["serde"] }
tfrecord = { version = "0.8.0", features = ["full"] }
chrono = "0.4.19"
tch-goodies = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "6ac6dc96e1e3e5b3d026a44d4ff382cb39983085" }
tch-modules = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "6ac6dc96e1e3e5b3d026a44d4ff382cb39983085" }
yolo-dl = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "6ac6dc96e1e3e5b3d026a44d4ff382cb39983085" }
train = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "6ac6dc96e1e3e5b3d026a44d4ff382cb39983085" }
iii-formosa-dataset = "0.2.0"
glob = "0.3.0"
serde-xml-rs = "0.4.1"
owning_ref = "0.4.1"
mona = "0.1.0"
num-traits = "0.2.14"
by_address = "1.0.4"
# tch-goodies = { version = "0.1.0", path = "../yolo-dl/tch-goodies" }
# tch-modules = { version = "0.1.0", path = "../yolo-dl/tch-modules" }

[profile.release]
debug = true
debug-assertions = false
overflow-checks = false
## enabling 'lto' improves the performance but results in
## very long compilation time.
lto = false
