[package]
name = "frame-flow"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.4.1"
anyhow = "1.0.40"
serde = { version = "1.0.126", features = ["derive"] }
json5 = "0.3.0"
structopt = "0.3.21"
tch-serde = "0.4.0"
rand = "0.8.3"
itertools = "0.10.0"
unzip-n = "0.1.2"
approx = "0.5.0"
tch-tensor-like = "0.3.0"
tokio = { version = "1.6.1", features = ["fs"] }
tokio-stream = { version = "0.1.6", features = ["fs"] }
futures = "0.3.15"
par-stream = { version = "0.3.1", features = ["runtime_tokio"] }
csv = "1.1.6"
indexmap = "1.6.2"
collected = "0.1.2"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
opentelemetry-jaeger = "0.13.0"
tracing-opentelemetry = "0.13.0"
noisy_float = { version = "0.2.0", features = ["serde"] }
tfrecord = { version = "0.7.0", features = ["full"] }
chrono = "0.4.19"
tch-goodies = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "1b0a8c9604dc5848d112d1fc40175c00643fac7d" }
tch-modules = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "1b0a8c9604dc5848d112d1fc40175c00643fac7d" }
# tch-goodies = { version = "0.1.0", path = "../yolo-dl/tch-goodies" }
# tch-modules = { version = "0.1.0", path = "../yolo-dl/tch-modules" }

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true
## enabling 'lto' improves the performance but results in
## very long compilation time.
lto = false
