[package]
name = "frame-flow"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.4.0"
anyhow = "1.0.38"
serde = { version = "1.0.124", features = ["derive"] }
json5 = "0.3.0"
structopt = "0.3.21"
gstreamer = "0.16.7"
gstreamer-app = "0.16.5"
tch-serde = "0.4.0"
opencv = "0.49.1"
rand = "0.8.3"
itertools = "0.10.0"
tch-goodies = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "9368cf5f743cdfc1259f2625290cb8ee4f22bf6f" }
unzip-n = "0.1.2"
approx = "0.4.0"
log = "0.4.14"
tch-tensor-like = "0.3.0"
