[package]
name = "frame-flow"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.4.0"
anyhow = "1.0.40"
serde = { version = "1.0.125", features = ["derive"] }
json5 = "0.3.0"
structopt = "0.3.21"
tch-serde = "0.4.0"
rand = "0.8.3"
itertools = "0.10.0"
tch-goodies = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "2dcc63f591e4a7c43a1c7efbd8215a66e0884b6b" }
# yolo-dl = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "2dcc63f591e4a7c43a1c7efbd8215a66e0884b6b" }
unzip-n = "0.1.2"
approx = "0.4.0"
tch-tensor-like = "0.3.0"
tokio = { version = "1.4.0", features = ["fs"] }
tokio-stream = { version = "0.1.5", features = ["fs"] }
futures = "0.3.13"
par-stream = { version = "0.3.1", features = ["runtime_tokio"] }
csv = "1.1.6"
indexmap = "1.6.2"
collected = "0.1.2"
tracing = "0.1.23"
tracing-subscriber = "0.2.15"
opentelemetry-jaeger = "0.11.0"
tracing-opentelemetry = "0.11.0"

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true
## enabling 'lto' improves the performance but results in
## very long compilation time.
lto = false
