[package]
name = "frame-flow"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.4.0"
anyhow = "1.0.40"
serde = { version = "1.0.125", features = ["derive"] }
json5 = "0.3.0"
structopt = "0.3.21"
tch-serde = "0.4.0"
rand = "0.8.3"
itertools = "0.10.0"
tch-goodies = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "c461baca23ec115e9bfbf754027c53a89d50652e" }
unzip-n = "0.1.2"
approx = "0.4.0"
tch-tensor-like = "0.3.0"
tokio = { version = "1.4.0", features = ["fs"] }
tokio-stream = { version = "0.1.5", features = ["fs"] }
futures = "0.3.14"
par-stream = { version = "0.3.1", features = ["runtime_tokio"] }
csv = "1.1.6"
indexmap = "1.6.2"
collected = "0.1.2"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
opentelemetry-jaeger = "0.12.1"
tracing-opentelemetry = "0.12.0"
noisy_float = { version = "0.2.0", features = ["serde"] }
tfrecord = { version = "0.7.0", features = ["full"] }
chrono = "0.4.19"

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true
## enabling 'lto' improves the performance but results in
## very long compilation time.
lto = false
