[package]
name = "frame-flow"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3.1"
anyhow = "1.0.38"
serde = { version = "1.0.123", features = ["derive"] }
json5 = "0.3.0"
structopt = "0.3.21"
gstreamer = "0.16.7"
gstreamer-app = "0.16.5"
tch-serde = "0.3.1"
opencv = "0.49.1"
rand = "0.8.3"
itertools = "0.10.0"
tch-goodies = { version = "0.1.0", git = "https://github.com/jerry73204/yolo-dl.git", rev = "f37cf74f" }
unzip-n = "0.1.2"
approx = "0.4.0"
log = "0.4.14"
